### ISSUE TITLE
Honeyd Scripts Needed: A List

### ISSUE THREAD

**Issue by awaldow** [DataSoft/Honeyd#13]
I went and sorted all the services on ports beneath 1024 (or the "well-defined" ports) from the nmap-services file in /usr/local/share/nmap by frequency; this, I think, will give us a good list as to what services should have scripts made, if possible (I have a feeling that it's going to be more of a community task for some of the proprietary protocols), and a way to prioritize what should be created first:

Service_Type: http_tcp
Port Number/Frequency: 80/48.4143

Service_Type: ipp_udp
Port Number/Frequency: 631/45.0281

Service_Type: snmp_udp
Port Number/Frequency: 161/43.3467

Service_Type: netbios-ns_udp
Port Number/Frequency: 137/36.5163

Service_Type: ntp_udp
Port Number/Frequency: 123/33.0879

Service_Type: netbios-dgm_udp
Port Number/Frequency: 138/29.783

Service_Type: microsoft-ds_udp
Port Number/Frequency: 445/25.3118

Service_Type: msrpc_udp
Port Number/Frequency: 135/24.4452

Service_Type: dhcps_udp
Port Number/Frequency: 67/22.801

Service_Type: telnet_tcp
Port Number/Frequency: 23/22.1265

Service_Type: domain_udp
Port Number/Frequency: 53/21.3496

Service_Type: https_tcp
Port Number/Frequency: 443/20.8669

Service_Type: ftp_tcp
Port Number/Frequency: 21/19.7667

Service_Type: netbios-ssn_udp
Port Number/Frequency: 139/19.3726

Service_Type: ssh_tcp
Port Number/Frequency: 22/18.2286

Service_Type: isakmp_udp
Port Number/Frequency: 500/16.3742

Service_Type: dhcpc_udp
Port Number/Frequency: 68/14.0118

Service_Type: route_udp
Port Number/Frequency: 520/13.9376

Service_Type: smtp_tcp
Port Number/Frequency: 25/13.1314

Service_Type: syslog_udp
Port Number/Frequency: 514/11.9804

Service_Type: snmptrap_udp
Port Number/Frequency: 162/10.3346

Service_Type: tftp_udp
Port Number/Frequency: 69/10.2835

These are all services that appear 10% or more of the time on hosts, according to the nmap-services file. Now, obviously some of these are already done, but I will leave the list in its entirety for review and for comments on the actual utility of the existing scripts.

Completed scripts: httpd (Linux and Windows), snmp (Unix(?)), telnet (only Linux, though there's a Windows entry in scripts.xml that uses the Linux script...), smtp (Linux), ssh (Windows and Linux), ftp (Windows and Linux)

**Comment by PherricOxide** [comment]
There's a netbios implementation here that might be worth taking a look at: http://www.chambet.com/tools.html
