### ISSUE TITLE
Create unified honeyd script parameter interface

### ISSUE THREAD

**Issue by altf4** [DataSoft/Honeyd#29]
One large challenge of using honeyd service scripts is that each one takes input from different sources and in different formats. What is needed is a single unified parameter format / interface such that any program can interact with the scripts. 

For instance, the Nova Web UI will want to provide input to many options in scripts. But without a unified way of providing this input, it would have to be hardcoded for each script.

**Comment by PherricOxide** [comment]
This is somewhat a duplicate of https://github.com/DataSoft/Honeyd/issues/9

**Comment by altf4** [comment]
Yes, dupe. Didn't see the other one.
