### ISSUE TITLE
Honeyd script lag/delay when waiting for input

### ISSUE THREAD

**Issue by PherricOxide** [DataSoft/Honeyd#3]
<b>Background</b>

Honeyd scripts that don't send anything to stdout before waiting for something on stdin will lag for about 2.5 seconds before input sent to the socket gets forwarded to the script's stdin. A script like telnet that sends information first will respond to input right away. However, a script like apache.sh which waits for input after the connection is established, such as "GET / /HTTP/1.1", will hang for several seconds before the "GET / /HTTP/1.1" is actually sent to the script's stdin and processed.

<b>Reproduction</b>

Set up the apache.sh or apache.tcl script on a port and bind that profile to an IP address.
View it in a web browser and you will notice the delay. 

To reproduce using just telnet,

telnet ip 80
Enter any text and press return
Press return again to send a blank line
You'll notice a delay before the webserver script responds.

<b>Debugging so far</b>

Relevant functions that were identified,

command.c/cmd_fork executes the script
command.c/cmd_trigger_write seems to trigger the function to write to the script's stdin

Call trace to cmd_trigger_write,

Thread [1] 18424 (Suspended : Breakpoint)  
    <b>cmd_trigger_write() </b>at command.c:92 0x8059740
    <b>tcp_add_readbuf() </b>at tcp.c:130 0x806cb7e
    <b>tcp_recv_cb() </b>at honeyd.c:2,181 0x80576ae
    <b>honeyd_dispatch()</b> at honeyd.c:2,779 0x80586eb
    <b>honeyd_delay_cb() </b>at honeyd.c:766 0x8058c93
    <b>honeyd_delay_packet()</b> at honeyd.c:833 0x80533fe
    <b>honeyd_input()</b>at honeyd.c:3,008 0x8058fbf
    <b>honeyd_recv_cb()</b> at honeyd.c:3,163 0x8059558 0x152d44
    <b>pcap_dispatch()</b> at 0x155548
    <b>interface_recv()</b> at interface.c:516 0x807106b
    <b>event_base_loop()</b>at 0x136114
    <b>event_loop()</b> at 0x136267
    <b>event_dispatch() </b>at 0x13628b
    <b>main()</b> at honeyd.c:3,622 0x8051c6c

I found through manually going through the call trace that the delay seems to happen somewhere inside <b>honeyd_recv_cb</b>. If you put a breakpoint in honeyd_input, there is already a few second delay before that breakpoint gets hit. honeyd_recv_cb seems to be getting hit as soon as the packet is received though. 

Viewing the exchange in wireshark makes it seem like it doesn't respond until a TCP KEEPALIVE packet is sent. Looking into this more could provide some clues on the problem.

**Comment by dscott3** [comment]
https://code.google.com/p/honeyd/issues/detail?id=6
In the above link they started droping all ack packets that arrived out of order because signed subtraction caused a perceived ack of nearly 4gb of data and an infinite loop.  Fixing the original bug and removing the 'fix' may resolve this issue as it makes sense that the delay is caused by packets arriving early and being dropped forcing the connection to wait for a keep-alive.

**Comment by PherricOxide** [comment]
This bug seems to have fixed itself with the libevent upgrade.
