### ISSUE TITLE
Hostnames not configurable, hardcoded default to "someone"

### ISSUE THREAD

**Issue by awaldow** [DataSoft/Honeyd#36]
This is going to be a problem going forward, it makes all of the haystack nodes easily distinguishable from real nodes after a scan. I don't know exactly how this gets done, but the hostname is hardcoded in the _pack_request() method in dhcpclient.c. 
It's hard to do something like this automagically, unless there's a user supplied list of acceptable hostnames or something that
can get put into an array and randomly grabbed; then there's concerns of # of hostnames available vs. # of nodes to be created, etc. It'll be a mess but it'll need to get done eventually.

**Comment by altf4** [comment]
Fixed in 174d4456cc0fc7e3d9ddf1ffaa97502c71daf942
