### ISSUE TITLE
DHCP Requests start timing out if too many honeypots

### ISSUE THREAD

**Issue by PherricOxide** [DataSoft/Honeyd#38]
If Honeyd has say 100 honeypots, it will make 100 DHCP requests immediately when it starts. The DHCP server will start responding to them a few (possibly one) at a time, and most of them will just end up timing out by the time the DHCP server gets around to making offers on all of them.

One solution would be rather than sending all of the requests when we start, to only send N > 0 DHCP request at a time, and don't send more requests until those N honeypots have gotten IP addresses.

**Comment by altf4** [comment]
Fixed in f3dff773d34f4d7f093269a2c6e825a97ed5c7d6

DHCP is now done in serial for each template
