### ISSUE TITLE
Make honeyd read ethernet ranges from file

### ISSUE THREAD

**Issue by ghost** [DataSoft/Honeyd#5]
The current method that honeyd uses to get a list of what hardware manufacturers belong to what MAC ranges, it just hardcodes the list into the source as a huge array. (in ethernet.c) 

We should instead make honeyd read the nmap-mac-prefixes file just like Nova does.

**Comment by DataSoft** [comment]
This will:
A) Make the list more complete
B) Make the list editable by the user easily. 
C) Make the list easily updatable. (Not get too old and out of date)

**Comment by PherricOxide** [comment]
The prefix file is located in /usr/share/nova/sharedFiles/nmap-mac-prefixes. It should really get copied somewhere from the Honeyd repository instead of the Nova repository, but for now just getting it to read that file is fine.

**Comment by Romstar** [comment]
fixed a1c2609632006e2daade56d0fa97b1a5920510a3
