### ISSUE TITLE
pydataprocessing.c Error on Compiling

### ISSUE THREAD

**Issue by nextrevision** [DataSoft/Honeyd#65]
During compilation, the build fails with errors related to pydataprocessing.c: pydataprocessing.c:400: error: expected expression before ‘.’ token

Removing the '.' from the end of line 400 and adding a ';' to the end of line 402 solved the issue for me.
## Before:

``` C
if (pValue == NULL) {
    PyErr_Print();.
    syslog(LOG_ERR,"%s: failed to build argument list",__func__)
}
```
## After:

``` C
if (pValue == NULL) {
    PyErr_Print();
    syslog(LOG_ERR,"%s: failed to build argument list",__func__);
}
```

**Comment by PherricOxide** [comment]
@nextrevision Thanks for the ticket! We don't usually compile with the python support, so we missed this one

@Romstar looks like it was when we changed more of the logging to syslog (https://github.com/DataSoft/Honeyd/commit/023459e513121aad5569e01af543625ae8af42d9#L24R400)

Go ahead and rebuild with python support enabled with,

```
 ./configure --with-python; make clean; make
```

And you should see this error (and be able to tell when it's fixed).
