### ISSUE TITLE
Make errors with CentOS

### ISSUE THREAD

**Issue by novaUd** [DataSoft/Honeyd#69]
Hi,

I am trying to get Honeyd to work with CentOS but when I do the make it gives me a bunch of errors. I found this issue which looks similar - https://github.com/DataSoft/Honeyd/issues/1

So if it is a libevent1-dev problem then how do I know which one CentOS would need? The one yum installs is 1.4.

The errors are ui.c warnings and errors.

**Comment by PherricOxide** [comment]
The current version of honeyd uses libevent2 (the old Honeyd 1.5c version used libevent1, but we upgraded to be compatible with the 2.x API.).

**Comment by novaUd** [comment]
Ok thanks, I installed libevent-2.0 and now it works, I did have to do the ./configure --without-python. Does that cause any problems down the road? honeyd seems to be working fine.

Thanks for the help,

**Comment by PherricOxide** [comment]
It shouldn't cause any problems with Nova/Honeyd. It will disable a few obscure features of honeyd (some extended control via honeydctl when running), but nothing we use should be disabled.
