### ISSUE TITLE
Honeyd Log Folder Permissions Problem

### ISSUE THREAD

**Issue by ghost** [DataSoft/Honeyd#7]
Honeyd demotes itself from root to the user "nobody:nogroup", but the make files/installer don't give file permissions to "nobody:nogroup" on /usr/share/nova/Logs.

We need to either change the user honeyd runs as (nova group?), change the file permissions on the Logs folder, or change where honeyd stuff logs to.

**Comment by PherricOxide** [comment]
This has become invalidated by Nova now setting permissions with the post install script for the /var/log/honeyd folder. 

A more general stand alone Honeyd (without Nova) solution is also to not hard code any log file paths in the scripts and leave it up to the user to specify the log folder location, making them responsibly for setting the permissions in whatever folder they choose. For this, see ticket #9.
