### ISSUE TITLE
Add tags !

### ISSUE THREAD

**Issue by sdiesbac** [DataSoft/Honeyd#75]
Hi all, 

why don't you tag your major commits for newer versions, and why don't you make tarball of them ??

It would much easier to follow the versions of Honeyd !

Cheers, 
Steve

**Comment by nullprobe** [comment]
Just download the ZIP (https://github.com/DataSoft/Honeyd/archive/master.zip) from the master branch?

**Comment by sdiesbac** [comment]
Ok for the zip, but why don't you tag your commits ??

Cheers, 
Steve

**Comment by altf4** [comment]
We do a monthly build cycle, so there's tags once a month for that build. Unless we forget to, which happens sometimes.

**Comment by altf4** [comment]
Oh, I just noticed that this was for Honeyd and not Nova. 

Umm, I guess there's no good reason for the lack of tags. Progress has been slow and incremental on honeyd, so I guess we never had that "Next Version" feel. Should probably do it anyway, you're right.

**Comment by PherricOxide** [comment]
Tagged the last build, we'll try and keep https://github.com/DataSoft/Nova and honeyd tagged at the same time from now on. Lot of times nothing will change in Honeyd for a month, so we forget to tag it.
