### ISSUE TITLE
SegFault when binding physical host

### ISSUE THREAD

**Issue by admb600** [DataSoft/Honeyd#81]
$ honeyd -V
Honeyd V1.5c Copyright (c) 2002-2007 Niels Provos
Honeyd Version 1.5c

$ uname -a
Linux ubuntu 3.5.0-23-generic #35~precise1-Ubuntu SMP Fri Jan 25 17:15:33 UTC 2013 i686 i686 i386 GNU/Linux

Issue:
I have a single physical host attached within a bunch of virtual hosts like below:

bind 81.223.40.102 linux
bind 81.223.40.104 to eth0          # physical host
bind 81.223.40.105 linux-sendmail
bind 81.223.40.244 pix
bind 81.223.40.249 windows-web
bind 81.223.40.250 windows-iis7
bind 81.223.40.251 windows-iis7
bind 81.223.40.254 router

If I start honeyd and then ping the physical host 81.223.40.104 I get a Segfault.

(gdb) run
Starting program: /usr/bin/honeyd -d -f /etc/honeypot/honeyd.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Honeyd V1.5c Copyright (c) 2002-2007 Niels Provos
honeyd[8334]: started with -d -f /etc/honeypot/honeyd.conf
honeyd[8334]: listening promiscuously on eth0: (arp or ip proto 47 or (udp and src port 67 and dst port 68) or (ip )) and not ether src aa:00:04:00:0a:04
honeyd[8334]: Running with root privileges.
honeyd[8334]: update_check: failed to resolve host.

Program received signal SIGSEGV, Segmentation fault.
0x08058960 in honeyd_delay_cb ()
(gdb) backtrace
#0  0x08058960 in honeyd_delay_cb ()
#1  0x0805311a in honeyd_delay_packet ()
#2  0x08058dc2 in honeyd_input ()
#3  0x08059318 in honeyd_recv_cb ()
#4  0xb7f7ce64 in ?? () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#5  0xb7f7f668 in pcap_dispatch () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#6  0x0806f764 in ?? ()
#7  0xb7fb2114 in event_base_loop () from /usr/lib/libevent-1.4.so.2
#8  0xb7fb2267 in event_loop () from /usr/lib/libevent-1.4.so.2
#9  0xb7fb228b in event_dispatch () from /usr/lib/libevent-1.4.so.2
#10 0x080519dc in main ()

(gdb) 

Any ideas?

**Comment by nullprobe** [comment]
Looks like the problem I had in #74

**Comment by PherricOxide** [comment]
1.5C is a fairly old version of honeyd; I would try updating to the newest version on our github and letting us know if you can still reproduce the problem.

**Comment by admb600** [comment]
Doh. Sorry guys, I took the latest release from honeyd.org. The latest version in the github repo fixes this as you said.

Thanks!
