### ISSUE TITLE
configure not finding libc.o on 64-bit (patch)

### ISSUE THREAD

**Issue by mojotoad** [DataSoft/Honeyd#82]
EDIT: Please delete this...the patch below pertains to an older honeyd code base (1.5c), my mistake.

I ran into the following issue while building from your source tree. The following patch appears to fix it:

http://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg264991.html

Thanks,
Matt

**Comment by PherricOxide** [comment]
Closed because bug was related to old version of honeyd (1.5c).
