### ISSUE TITLE
The --verify-config option always exits with status code 1

### ISSUE THREAD

**Issue by mojotoad** [DataSoft/Honeyd#83]
As stated above, the exit code is 1 even if parsing the config file was successful. In addition, root is required in order to do this...it would be more useful if non-privileged accounts could check the syntax of config files.

**Comment by PherricOxide** [comment]
You shouldn't reed root to run --verify-config; does it give you a specific error when you run it without root?

**Comment by mojotoad** [comment]
Here's what I'm seeing:

[honeyd@localhost ~]$ honeyd --verify-config -f ./honeyd.conf
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[22436]: started with --verify-config -f ./honeyd.conf
Error: Could not change owner of ~/.config/honeyd: Operation not permitted
honeyd[22436]: pcap_lookupdev: no suitable device found

Also...I think this must be something else entirely, but if I use "-f honeyd.conf" (no preceding "./") then it core dumps...no idea what that is.

EDIT: Just for completeness, if I pass it a nonexistent path it's the same result:

[honeyd@localhost ~]$ honeyd --verify-config -f /flurble/bubble.conf
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[22700]: started with -d --verify-config -f /flurble/bubble.conf
Error: Could not change owner of ~/.config/honeyd: Operation not permitted
honeyd[22700]: pcap_lookupdev: no suitable device found

**Comment by PherricOxide** [comment]
What are the permissions on ~/.config/honeyd?
